config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  post 'tasks', to: 'tasks#create'

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <div class='mb-3'>
    <%= f.label :title, class:'form-label' %>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class='mb-3'>
    <%= f.label :details, class:'form-label'  %>
    <%= f.text_area :details, class:'form-control' %>
  </div>
  <div class='mb-3'>
    <%= f.check_box :completed %>
    <%= f.label :completed, 'Task Completed' %>
  </div>
  <div class='mb-3'>
    <%= f.submit :'Submit Task', class:'btn btn-primary'%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class='container'>
  <h1 class='pt-5'>Edit Task </h1>
  <%= render "form", task: @task %>

  <div class='mt-5'>
    <hr>
    <%= link_to tasks_path, class:'mt-5' do %>
      <i class="fa-solid fa-clock-rotate-left"></i>
      <%=  "Back to Index" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class='container'>
  <h1 class='mb-5 p-4 index-title'>My Tasks</h1>

  <ul id='index_ul'>
    <% @tasks.each do |task| %>
      <li class='mb-2'>
        <% if task.completed %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task) %>
        -
        <%= link_to task_path(task), class:'teste', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash-can"></i>
          <%= ""%>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class='mt-5'>
    <hr>
    <%= link_to 'Add new task', tasks_new_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class='container'>
  <h1>New Task</h1>
  <%= render "form", task: @task %>

  <div class='mt-5'>
    <hr>
    <%= link_to tasks_path, class:'mt-5' do %>
      <i class="fa-solid fa-clock-rotate-left"></i>
      <%=  "Back to Index" %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class='container'>

  <div class='mb-5'>
    <div class='task-title'>
      <h2 class='mb-5 p-4'><%= @task.title %></h2>

      <%= link_to task_edit_path, class:'teste' do %>
        <div class='btn btn-secondary btn-lg'>
          <i class="fa-solid fa-pen-to-square"></i>
          <%=  "Edit Task" %>
        </div>
      <% end %>
    </div>

    <p id='details-card' class='p-4'><%= @task.details %></p>
    <br>
    <% if @task.completed %>

      <i class="fa-regular fa-square-check"></i> <span>This task is completed</span>
    <% else %>
      <i class="fa-regular fa-square"></i> <span>This task is not completed yet</span>
    <% end %>
  </div>

  <%= link_to task_path(@task), class:'me-3', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    <i class="fa-solid fa-trash-can"></i>
    <%= " Delete"%>
  <% end %>


  <%= link_to tasks_path, class:'teste' do %>
    <i class="fa-solid fa-clock-rotate-left"></i>
    <%=  "Back to Index" %>
  <% end %>
</div>